//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATM.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Operations = new HashSet<Operation>();
        }
    
        public long ID { get; set; }
        public string Number { get; set; }
        public string PinCode { get; set; }
        public int FailedLogins { get; set; }
        public decimal Balance { get; set; }
        public Nullable<byte> BlockReason { get; set; }
        public short CurrencyCode { get; set; }
    
        public virtual ICollection<Operation> Operations { get; set; }
    }
}
